Static frontend complete
FEC-LEGO/gallery pull request #3
Opened 2020-09-30 16:40 UTC by Henry-C-Lo

need to work on functionality and full screen button

2020-09-30 16:49 UTC, songkenny commented on client/src/components/App.jsx
> +          <GalleryItemList galleryImages={galleryImages} />
Recommend putting all of GalleryItemList into App

2020-09-30 16:58 UTC, songkenny requested changes

2020-09-30 16:58 UTC, songkenny commented on client/src/components/GalleryItemList.jsx
> +}
Delete this component

2020-10-02 17:37 UTC, ucb15erickao commented on coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Find out what this is

2020-10-02 17:41 UTC, ucb15erickao commented on tests/App.test.js
> +    expect(wrapper.exists()).toBeTruthy();
I like this test. It doesn't need to work, it's okay.

2020-10-02 17:42 UTC, ucb15erickao commented on yarn-error.log
> +Arguments:
git ignore

2020-10-02 17:43 UTC, merged